export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    POPULAR_REFRESH: 'POPULAR_REFRESH',  // popular页刷新
    POPULAR_REFRESH_SUCCESS: 'LOAD_POPULAR_SUCCESS',  // 下拉刷新成功
    POPULAR_REFRESH_FAIL: 'LOAD_POPULAR_FAIL',  // 下拉刷新失败
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', // 上拉加载更多成功
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',   // 上拉加载更多失败
    POPULAR_FLUSH_FAVORITE: 'POPULAR_FLUSH_FAVORITE', // 刷新流行的收藏状态

    TRENDING_REFRESH: 'TRENDING_REFRESH',  // TRENDING页刷新
    TRENDING_REFRESH_SUCCESS: 'LOAD_TRENDING_SUCCESS',  // 下拉刷新成功
    TRENDING_REFRESH_FAIL: 'LOAD_TRENDING_FAIL',  // 下拉刷新失败
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', // 上拉加载更多成功
    TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',   // 上拉加载更多失败
    TRENDING_FLUSH_FAVORITE: 'TRENDING_FLUSH_FAVORITE', // 刷新流行的收藏状态

    FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',   // 收藏加载
    FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',  // 收藏加载成功
    FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',  //收藏加载失败

    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS'
};